apiVersion: v1
kind: Service
metadata:
  name: security-service-svc
  labels:
    app: security-service-lbl
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: security-service-lbl