apiVersion: v1
  kind: ConfigMap
  metadata:
    name: security-config
  data:
    KEYCLOAK_URL: http://keycloak:80
    REALM: mytest1
    CLIENT_ID: keycloak-integration-app
    CLIENT_SECRET: rtie2DB14I9oab6XvGGDWa4OpSd5cqdq
    REDIRECT_URL: http://localhost:30000/security/oauth2
    AUTH_URL: http://keycloak:80/realms/mytest1/protocol/openid-connect/auth
    TOKEN_URL: http://keycloak:80/realms/mytest1/protocol/openid-connect/token
    HOME_PAGE_URL: http://localhost:30000/frontend